### ISSUE TITLE
Bug: many items cannot be searched and selected from the dropdown

### ISSUE THREAD

**Issue by alranel** [italia/developers-italia-onboarding#38]
When searching for _"Comune di Roma"_ I get the first 4 results matching that search query, but the one I'm looking for (Comune di Roma!) is not there and I cannot select it:

![screen shot 2019-02-07 at 19 19 14](https://user-images.githubusercontent.com/594957/52433475-72141a00-2b0d-11e9-98ea-9f0ce417b382.png)

We should either allow scrolling the drop down without limiting it to the first 4 results, or revert to a stricter, non-fulltext search.

**Comment by libremente** [comment]
Fixed in https://github.com/italia/developers-italia-onboarding/pull/41. 
See: https://github.com/italia/developers-italia-onboarding/blob/c8da62d2698dc56141e7a19848fbbf3a24f3ee65/public/assets/js/main.js#L7
I don't think this is a solution, it's just enlarging the slice of the search. However, with a proper keyword it should work better than before.

**Comment by libremente** [comment]
I would say that this has been fixed by #48. Closing.
