### ISSUE TITLE
Bug: bitbucket.org URLs are not accepted

### ISSUE THREAD

**Issue by alranel** [italia/developers-italia-onboarding#66]
We got a report from a user who is trying to register a URL in the https://bitbucket.org/xxx/ form. It looks like it's being rejected by the onboarding portal

**Comment by sebbalex** [comment]
bitbucket.org is whitelisted and correctly accepted, user were rejected because of `_` char in org name.
As for this [regex](https://github.com/italia/developers-italia-onboarding/blob/master/src/validator.js#L14) that char is ignored and will trigger a validation error.
Validation will be corrected allowing that char.
